### ISSUE TITLE
Add commit / patch support?

### ISSUE THREAD

**Issue by al-the-x** [alexdavid/vim-min-git-status#7] opened 2016-07-14 17:39 UTC
Some of the best features of `:Gstatus` were `p` to start `git add --patch` and `cc` to commit the staged file. Consider adding those shortcuts to `Gministatus` as well?

**Comment by alexdavid** [comment] 2016-07-17 18:06
@al-the-x: I added both shortcuts. Let me know if you have any issues with them.

**Comment by al-the-x** [comment] 2016-07-18 20:43
The patch shortcut doesn't properly wait for input. It runs `git add --patch` and displays the diff for the first block and the typical "Press Enter to continue" prompt from an external command.

**Comment by alexdavid** [comment] 2016-07-18 21:09
That's strange, it's working for me.  What shell is your vim configured to use? (`:set shell`)

![screen shot 2016-07-18 at 2 08 16 pm](https://cloud.githubusercontent.com/assets/751581/16930472/35f370c2-4cf1-11e6-8185-a8ff9a28cc4d.png)

**Comment by alexdavid** [comment] 2016-10-19 03:05
@al-the-x Are you still having this issue?

**Comment by alexdavid** [comment] 2017-05-11 22:33
Closing this issue because I'm unable to reproduce. Let me know if you still are having this issue

**Closed by alexdavid** 2017-05-11 22:33 UTC
